_nod: nod_
and damien tournoud: Damien Tournoud
berdir: Berdir
bleen18: bleen
cam8001: Cameron Tod
chx: Not specified
damz: Damien Tournoud
dan reinders: SpartyDan
davereid: Dave Reid
david rothstein: David_Rothstein
davinder.snehi: snehi
dereine: dawehner
developermitesh: miteshmap
dmitrydrozdik: ddrozdik
dominique clause: Dom.
ellatheharpy: shnark
emma_maria: emma.maria
floydm: floydm
follow up yched: yched
fubhy the cat: fubhy
gnugeti: gnuget
hardik.p: hardikpandya
heyrocker: gdd
ianmthomasuk: ianthomas_uk
janstoeckler: jan.stoeckler
javier.alejandr...: Not specified
jcventura: jcnventura
jeroen12345: JeroenT
joelpitett: joelpittet
juampy: juampynr
juanmamr: jmmarquez
lewis nyman: LewisNyman
lewisnyman: LewisNyman
lewisnyman bartik: LewisNyman
lokeoke: l0ke
long wave: longwave
malavya: imalabya
mark carver: markcarver
mark conroy: markconroy
moshe weitzmann: moshe weitzman
nguerrero: nesta_
niklas: Niklas Fiekas
no_commit_credit: xjm
nod: nod_
not_chx: Not specified
rhm50: rhm5000
rob loach: RobLoach
rocket_nova: drupal_was_my_past
rootatwc: ParisLiakos
sivaji@knackforge.com: Sivaji
shashi1028: shashikant_chauhan
smiro: smira
tim-diels: tim_diels
tim.plunket: tim.plunkett
typhonius: adammalone
yogesh pawar: yogeshmpawar
drpal: alwaysworking
